name: Mirroring

on: [push, delete]

# from: https://github.com/pixta-dev/repository-mirroring-action
jobs:
  to_codecommit:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ssh://${{ secrets.CODECOMMIT_REPO_URL }}
        ssh_private_key: # ssh-keygen -C "github-codecommit-sync-key" -N "" -f ./id_rsa -t rsa
          ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY }}
        ssh_username:
          ${{ secrets.CODECOMMIT_SSH_PRIVATE_KEY_ID }}
